Error running grunt build even without changes. Running "component:main" (component) task /Users/dima/dev/lucidworks/tv4/node_modules/source-map-support/source-map-support.js:154   if (!error || !error.stack) {                       ^
TypeError: CallSite method isNative expects CallSite as receiver
tv4.js should be good to use but sourcemaps will be broken I guess